### PR TITLE
Exception handling and proper logging tool

### PR DESCRIPTION
**Pull request by miaucl**
Hello @eliasball @Dielee,

I am a frequent user of Bring and Home Assistant, which is a open source home automation system: https://www.home-assistant.io

I stumbled across your implementation of the Bring API and I would like to use it to create an integration with home assistant.  A big thank you for your work already!
I hope this is fine with you guys, but to do so, I would first like to clean some things up if possible.

It is PR, I already added proper Exception handling which is required by home assistant and the usage of logging instead of prints, which better handles what logs are visible.

Further, I would like to also convert to async: https://github.com/eliasball/python-bring-api/pull/7. But this would be a breaking change and maybe it would be great to discuss that with you guys :)

### CODE REVIEW

**Comment by eliasball** [comment]
Hey @miaucl,
I appreciate the work, from a first look I think that the changes look really good! I will have time to give the changes a closer look after the first of January and then accept the PR, hope this is not too late for you :)
Until then, cheers!

**Comment by miaucl** [comment]
Hey, no worries! Have a look at it when you have time. If there are any questions, feel free 😄

**Comment by tr4nt0r** [comment]
Well, what a coincidence ^^ 
I just recently started to learn python and i also wanted to create a home assistant component for bring as one of my first projects in python. But i really appreciate that someone way more experienced than me is working on it. If there is anything i can do to help...

**Comment by miaucl** [comment]
> Well, what a coincidence ^^ 
> 
> I just recently started to learn python and i also wanted to create a home assistant component for bring as one of my first projects in python. But i really appreciate that someone way more experienced than me is working on it. If there is anything i can do to help...

Haha, nice! You might want to hit me up on discord (@miaucl) if you are motivated to work on it. I will first wait for this library to be ready.

**Comment by eliasball** [comment]
Merged!
I made some changes to the naming conventions and the logging and further differentiated the types and the exception classes to make it even more clear and uniform.
Good job @miaucl, appreciate the work!

**Comment by miaucl** [comment]
> Merged! I made some changes to the naming conventions and the logging and further differentiated the types and the exception classes to make it even more clear and uniform. Good job @miaucl, appreciate the work!

Thank you @eliasball for the quick response. Sure, it looks even better and clearer now :)

**Pull request merged**
